### ISSUE TITLE
p.2-0 섹터별 그래프 이슈

### ISSUE THREAD

**Issue by chaeyeonan** [finble-dev/Finble-FE#12]
p.2-0 첫번째 섹션에 종목별 도넛 그래프 / 섹터별 일자 그래프가 있는데 섹터별 그래프에 대한 고민.!

백엔드에서 데이터가 어떤 형식으로 넘어오는지 모르는 상태
만일 섹터별이 아니라 항목별로 넘어온다면 ( ex ) { 종목 이름 / 섹터 / 비율 }
프론트에서 따로 섹터를 묶어야하는 상황

- solve 1
프론트에서 섹션끼리 따로 묶고, 그 섹션에 해당하는 종목 비율을 다 더해서 그래프로 만들어준다. 비율 내림차순도 프론트에서 정렬

- solve 2
백엔드에 섹션별 비율을 서버로 보내달라고 요청한다

프론트단에서 처리할 수 있을 것 같긴한데 조금 번거로울 것 같긴해서 .. 어떻게하면 좋을까욧 .. 고민~~

**Comment by JeeeunOh** [comment]
원래 데이터 가공하는 로직적인 부분은 백에서 다 해주는게 맞지!!!! 가공해서 달라구 하자 오늘 ㅋㅋㅋㅋㅋ

**Comment by chaeyeonan** [comment]
회의 결과 백엔드에서 섹션별 비율 데이터 넘겨주는걸로 타협 .!
