### ISSUE TITLE
Chart.js 사용 이슈

### ISSUE THREAD

**Issue by JeeeunOh** [finble-dev/Finble-FE#6]
### 현재 우리 그래프

<img width="1111" alt="image" src="https://user-images.githubusercontent.com/65931227/211144125-8cab6eff-420d-49ee-bcde-c1cf5541550b.png">

### 그려야하는 그래프

<img width="760" alt="image" src="https://user-images.githubusercontent.com/65931227/211144176-c8e4a68b-27a4-4732-8895-1e5d2dc8c931.png">

### 해야하는 것
option 설정에 
1. x축 없애는 기능
2. 라벨링 left 정렬 기능
3. 툴팁 보이기 기능

을 넣어야하는데 option 설정이 하.나.도 안먹어..왜일까...

### 관련코드
src/pages/Lab/components/Result.tsx

**Comment by chaeyeonan** [comment]
** 1번 x축 없애는 기능 해결 방법

- yAixes / xAixes..? (이름 정확x) 를 그냥 x, y 로 수정
- options 에서 scales x/y 부분 대괄호 아니고 중괄호로 수정
- x 축 grid : display false 지정

**Comment by JeeeunOh** [comment]
2번, 3번 해결법 )

```
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Tooltip,
  Legend,
} from 'chart.js';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Tooltip,
  Legend
);
```

와 같이 툴팁과 범례 기능을 chart에 register 해줘야 한다.
